init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  
install:
  - ps: Start-FileDownload "https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/rrpam-wds/artifacts/service/setup.exe?job=Environment%3A%20PYTHON_VERSION%3D3.4%2C%20USE_QT_API%3DPyQt5%2C%20PYTHON_ARCH%3D32%2C%20PLATFORM%3Dx86%2C%20PYTEST_QT_API%3Dpyqt5" -FileName setup.exe
  - ps: Start-FileDownload "https://sourceforge.net/projects/innounp/files/latest/download" -FileName file.rar
  - cinst -y unrar
  - unrar x file.rar
  - dir 
  - innounp -x setup.exe -d.\rrpamwds > log
# no sikuli - ps: Start-FileDownload "https://launchpad.net/sikuli/sikulix/1.1.0/+download/sikulixsetup-1.1.0.jar"
# no sikuli  - java -jar sikulixsetup-1.1.0.jar options 1.1 
 
build: off

test_script:
  - ps: C:\\projects\\rrpam-wds-exetest\\run.ps1 



  
   
